// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/room.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TranscriptUrl *string                `protobuf:"bytes,2,opt,name=transcript_url,json=transcriptUrl,proto3,oneof" json:"transcript_url,omitempty"`
	SummaryUrl    *string                `protobuf:"bytes,3,opt,name=summary_url,json=summaryUrl,proto3,oneof" json:"summary_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_proto_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoomRequest) GetTranscriptUrl() string {
	if x != nil && x.TranscriptUrl != nil {
		return *x.TranscriptUrl
	}
	return ""
}

func (x *UpdateRoomRequest) GetSummaryUrl() string {
	if x != nil && x.SummaryUrl != nil {
		return *x.SummaryUrl
	}
	return ""
}

type GetParticipantIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantIDsRequest) Reset() {
	*x = GetParticipantIDsRequest{}
	mi := &file_proto_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantIDsRequest) ProtoMessage() {}

func (x *GetParticipantIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantIDsRequest.ProtoReflect.Descriptor instead.
func (*GetParticipantIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{1}
}

func (x *GetParticipantIDsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetParticipantIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantIDsResponse) Reset() {
	*x = GetParticipantIDsResponse{}
	mi := &file_proto_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantIDsResponse) ProtoMessage() {}

func (x *GetParticipantIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantIDsResponse.ProtoReflect.Descriptor instead.
func (*GetParticipantIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{2}
}

func (x *GetParticipantIDsResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_proto_room_proto protoreflect.FileDescriptor

const file_proto_room_proto_rawDesc = "" +
	"\n" +
	"\x10proto/room.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x98\x01\n" +
	"\x11UpdateRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x0etranscript_url\x18\x02 \x01(\tH\x00R\rtranscriptUrl\x88\x01\x01\x12$\n" +
	"\vsummary_url\x18\x03 \x01(\tH\x01R\n" +
	"summaryUrl\x88\x01\x01B\x11\n" +
	"\x0f_transcript_urlB\x0e\n" +
	"\f_summary_url\"3\n" +
	"\x18GetParticipantIDsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"6\n" +
	"\x19GetParticipantIDsResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds2\x97\x01\n" +
	"\vRoomService\x12:\n" +
	"\n" +
	"UpdateRoom\x12\x12.UpdateRoomRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x11GetParticipantIDs\x12\x19.GetParticipantIDsRequest\x1a\x1a.GetParticipantIDsResponse\"\x00B+Z)github.com/YaLaewWa/tamlayka-shared/protob\x06proto3"

var (
	file_proto_room_proto_rawDescOnce sync.Once
	file_proto_room_proto_rawDescData []byte
)

func file_proto_room_proto_rawDescGZIP() []byte {
	file_proto_room_proto_rawDescOnce.Do(func() {
		file_proto_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_room_proto_rawDesc), len(file_proto_room_proto_rawDesc)))
	})
	return file_proto_room_proto_rawDescData
}

var file_proto_room_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_room_proto_goTypes = []any{
	(*UpdateRoomRequest)(nil),         // 0: UpdateRoomRequest
	(*GetParticipantIDsRequest)(nil),  // 1: GetParticipantIDsRequest
	(*GetParticipantIDsResponse)(nil), // 2: GetParticipantIDsResponse
	(*emptypb.Empty)(nil),             // 3: google.protobuf.Empty
}
var file_proto_room_proto_depIdxs = []int32{
	0, // 0: RoomService.UpdateRoom:input_type -> UpdateRoomRequest
	1, // 1: RoomService.GetParticipantIDs:input_type -> GetParticipantIDsRequest
	3, // 2: RoomService.UpdateRoom:output_type -> google.protobuf.Empty
	2, // 3: RoomService.GetParticipantIDs:output_type -> GetParticipantIDsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_room_proto_init() }
func file_proto_room_proto_init() {
	if File_proto_room_proto != nil {
		return
	}
	file_proto_room_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_room_proto_rawDesc), len(file_proto_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_proto_goTypes,
		DependencyIndexes: file_proto_room_proto_depIdxs,
		MessageInfos:      file_proto_room_proto_msgTypes,
	}.Build()
	File_proto_room_proto = out.File
	file_proto_room_proto_goTypes = nil
	file_proto_room_proto_depIdxs = nil
}
