// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/room_user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomUserService_GetParticipantIDs_FullMethodName = "/RoomUserService/GetParticipantIDs"
)

// RoomUserServiceClient is the client API for RoomUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomUserServiceClient interface {
	GetParticipantIDs(ctx context.Context, in *GetParticipantIDsRequest, opts ...grpc.CallOption) (*GetParticipantIDsResponse, error)
}

type roomUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomUserServiceClient(cc grpc.ClientConnInterface) RoomUserServiceClient {
	return &roomUserServiceClient{cc}
}

func (c *roomUserServiceClient) GetParticipantIDs(ctx context.Context, in *GetParticipantIDsRequest, opts ...grpc.CallOption) (*GetParticipantIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParticipantIDsResponse)
	err := c.cc.Invoke(ctx, RoomUserService_GetParticipantIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomUserServiceServer is the server API for RoomUserService service.
// All implementations must embed UnimplementedRoomUserServiceServer
// for forward compatibility.
type RoomUserServiceServer interface {
	GetParticipantIDs(context.Context, *GetParticipantIDsRequest) (*GetParticipantIDsResponse, error)
	mustEmbedUnimplementedRoomUserServiceServer()
}

// UnimplementedRoomUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomUserServiceServer struct{}

func (UnimplementedRoomUserServiceServer) GetParticipantIDs(context.Context, *GetParticipantIDsRequest) (*GetParticipantIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParticipantIDs not implemented")
}
func (UnimplementedRoomUserServiceServer) mustEmbedUnimplementedRoomUserServiceServer() {}
func (UnimplementedRoomUserServiceServer) testEmbeddedByValue()                         {}

// UnsafeRoomUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomUserServiceServer will
// result in compilation errors.
type UnsafeRoomUserServiceServer interface {
	mustEmbedUnimplementedRoomUserServiceServer()
}

func RegisterRoomUserServiceServer(s grpc.ServiceRegistrar, srv RoomUserServiceServer) {
	// If the following call panics, it indicates UnimplementedRoomUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomUserService_ServiceDesc, srv)
}

func _RoomUserService_GetParticipantIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomUserServiceServer).GetParticipantIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomUserService_GetParticipantIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomUserServiceServer).GetParticipantIDs(ctx, req.(*GetParticipantIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomUserService_ServiceDesc is the grpc.ServiceDesc for RoomUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RoomUserService",
	HandlerType: (*RoomUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetParticipantIDs",
			Handler:    _RoomUserService_GetParticipantIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/room_user.proto",
}
