// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/room_user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetParticipantIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantIDsRequest) Reset() {
	*x = GetParticipantIDsRequest{}
	mi := &file_proto_room_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantIDsRequest) ProtoMessage() {}

func (x *GetParticipantIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantIDsRequest.ProtoReflect.Descriptor instead.
func (*GetParticipantIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetParticipantIDsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetParticipantIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantIDsResponse) Reset() {
	*x = GetParticipantIDsResponse{}
	mi := &file_proto_room_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantIDsResponse) ProtoMessage() {}

func (x *GetParticipantIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantIDsResponse.ProtoReflect.Descriptor instead.
func (*GetParticipantIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetParticipantIDsResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_proto_room_user_proto protoreflect.FileDescriptor

const file_proto_room_user_proto_rawDesc = "" +
	"\n" +
	"\x15proto/room_user.proto\"3\n" +
	"\x18GetParticipantIDsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"6\n" +
	"\x19GetParticipantIDsResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds2_\n" +
	"\x0fRoomUserService\x12L\n" +
	"\x11GetParticipantIDs\x12\x19.GetParticipantIDsRequest\x1a\x1a.GetParticipantIDsResponse\"\x00B+Z)github.com/YaLaewWa/tamlayka-shared/protob\x06proto3"

var (
	file_proto_room_user_proto_rawDescOnce sync.Once
	file_proto_room_user_proto_rawDescData []byte
)

func file_proto_room_user_proto_rawDescGZIP() []byte {
	file_proto_room_user_proto_rawDescOnce.Do(func() {
		file_proto_room_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_room_user_proto_rawDesc), len(file_proto_room_user_proto_rawDesc)))
	})
	return file_proto_room_user_proto_rawDescData
}

var file_proto_room_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_room_user_proto_goTypes = []any{
	(*GetParticipantIDsRequest)(nil),  // 0: GetParticipantIDsRequest
	(*GetParticipantIDsResponse)(nil), // 1: GetParticipantIDsResponse
}
var file_proto_room_user_proto_depIdxs = []int32{
	0, // 0: RoomUserService.GetParticipantIDs:input_type -> GetParticipantIDsRequest
	1, // 1: RoomUserService.GetParticipantIDs:output_type -> GetParticipantIDsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_room_user_proto_init() }
func file_proto_room_user_proto_init() {
	if File_proto_room_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_room_user_proto_rawDesc), len(file_proto_room_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_user_proto_goTypes,
		DependencyIndexes: file_proto_room_user_proto_depIdxs,
		MessageInfos:      file_proto_room_user_proto_msgTypes,
	}.Build()
	File_proto_room_user_proto = out.File
	file_proto_room_user_proto_goTypes = nil
	file_proto_room_user_proto_depIdxs = nil
}
